In [1]:
import pandas as pd
import numpy as np

In [9]:
data=pd.read_csv('Loan_updated1.csv')

In [15]:
data.head(10)

,Loan_ID,Customer_ID,Loan_Type,Sanction_Amount,Interest_Rate,Tenure_Months,EMI,Loan_Status,Branch
0,LOAN29295,CUST3535,Auto Loan,4192271,12.05,180,50449.23,unknown,trivandrum
1,LOAN77532,CUST7725,Auto Loan,455031,13.53,60,10477.23,closed,kochi
2,LOAN37815,CUST6170,Home Loan,6708773,11.90,12,595752.56,unknown,kochi
3,LOAN11630,CUST1614,Business Loan,9643003,11.04,12,852444.53,unknown,calicut
4,LOAN23871,CUST2308,Personal Loan,6208981,7.31,60,123855.41,active,chennai
5,LOAN52689,CUST9027,Home Loan,1180431,13.95,180,15680.65,active,chennai
6,LOAN56908,CUST4780,Home Loan,5652235,11.77,60,125074.89,active,calicut
7,LOAN69584,CUST1003,Auto Loan,7285879,12.04,240,80427.07,default,kochi
8,LOAN10616,CUST2951,Personal Loan,8161861,12.83,24,387378.34,closed,chennai
9,LOAN36633,CUST2010,Home Loan,3866162,9.09,24,176784.31,unknown,calicut

In [13]:
#cleaning signs from data
data['Interest_Rate']=data['Interest_Rate'].str.replace('%','',regex=True)
data['Branch']=data['Branch'].str.lower()

In [13]:
data['Branch']=data['Branch'].str.strip()

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Loan_ID          5000 non-null   object
 1   Customer_ID      5000 non-null   object
 2   Loan_Type        5000 non-null   object
 3   Sanction_Amount  5000 non-null   int64
 4   Interest_Rate    5000 non-null   object
 5   Tenure_Months    5000 non-null   int64
 6   EMI              5000 non-null   float64
 7   Loan_Status      5000 non-null   object
 8   Branch           5000 non-null   object
dtypes: float64(1), int64(2), object(6)
memory usage: 351.7+ KB

In [19]:
loan_unknown=data[data['Loan_Status']=='unknown']

In [21]:
loan_unknown.head()

,Loan_ID,Customer_ID,Loan_Type,Sanction_Amount,Interest_Rate,Tenure_Months,EMI,Loan_Status,Branch
0,LOAN29295,CUST3535,Auto Loan,4192271,12.05,180,50449.23,unknown,trivandrum
2,LOAN37815,CUST6170,Home Loan,6708773,11.9,12,595752.56,unknown,kochi
3,LOAN11630,CUST1614,Business Loan,9643003,11.04,12,852444.53,unknown,calicut
9,LOAN36633,CUST2010,Home Loan,3866162,9.09,24,176784.31,unknown,calicut
12,LOAN29922,CUST2986,Home Loan,6321714,11.21,24,295258.15,unknown,calicut

In [17]:
loan_unknown.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1323 entries, 0 to 4996
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Loan_ID          1323 non-null   object
 1   Customer_ID      1323 non-null   object
 2   Loan_Type        1323 non-null   object
 3   Sanction_Amount  1323 non-null   int64
 4   Interest_Rate    1323 non-null   object
 5   Tenure_Months    1323 non-null   int64
 6   EMI              1323 non-null   float64
 7   Loan_Status      1323 non-null   object
 8   Branch           1323 non-null   object
dtypes: float64(1), int64(2), object(6)
memory usage: 103.4+ KB

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Loan_ID          5000 non-null   object
 1   Customer_ID      5000 non-null   object
 2   Loan_Type        5000 non-null   object
 3   Sanction_Amount  5000 non-null   int64
 4   Interest_Rate    5000 non-null   object
 5   Tenure_Months    5000 non-null   int64
 6   EMI              5000 non-null   float64
 7   Loan_Status      5000 non-null   object
 8   Branch           5000 non-null   object
dtypes: float64(1), int64(2), object(6)
memory usage: 351.7+ KB

In [27]:
#checking duplicated datas 
dup=data.duplicated()
#print(dup.count())

In [17]:
data.to_csv('E:\Data Analysis\Project\Loan\loan_updated1.csv',index=False)

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Admin\AppData\Local\Temp\ipykernel_18076\1694617061.py:1: SyntaxWarning: invalid escape sequence '\D'
  data.to_csv('E:\Data Analysis\Project\Loan\loan_updated1.csv',index=False)

In [3]:
df4=pd.read_csv('Loan_risk.csv')

In [7]:
df5=df4.copy()

In [11]:
#create a surrogate loan_id

df5['Loan_uid'] = range ( 1 , len(df5) + 1)

df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Loan_ID          5000 non-null   object
 1   Customer_ID      5000 non-null   object
 2   Loan_Type        5000 non-null   object
 3   Sanction_Amount  5000 non-null   int64
 4   Interest_Rate    5000 non-null   float64
 5   Tenure_Months    5000 non-null   int64
 6   EMI              5000 non-null   float64
 7   Loan_Status      5000 non-null   object
 8   Branch           5000 non-null   object
 9   Income           5000 non-null   int64
 10  Credit_score     5000 non-null   int64
 11  Monthly_Income   5000 non-null   float64
 12  DTI              5000 non-null   float64
 13  LTI              5000 non-null   float64
 14  Emi_burden       5000 non-null   float64
 15  Interest_burden  5000 non-null   float64
 16  Credit_risk      5000 non-null   object
 17  default_flag     5000 non-null   int64
 18  PD               5000 non-null   float64
 19  cluster_raw      5000 non-null   int64
 20  Clusters         5000 non-null   int64
 21  Loan_uid         5000 non-null   int64
dtypes: float64(8), int64(8), object(6)
memory usage: 859.5+ KB

In [15]:
df5.to_csv('E:\Data Analysis\Project\Loan\Loan_risk.csv',index=False)

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Admin\AppData\Local\Temp\ipykernel_14684\3120478002.py:1: SyntaxWarning: invalid escape sequence '\D'
  df5.to_csv('E:\Data Analysis\Project\Loan\Loan_risk.csv',index=False)