In [1]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv('Transaction_updated.csv')

In [15]:
data.head()

,Transaction_ID,Customer_ID,Branch,Transaction_Date,Transaction_Type,Amount,Currency,Status,Amount_in_INR
0,TXN833420,CUST2665,TRIVANDRUM,2023-01-07,DEPOSIT,389650.0,INR,UNKNOWN,389650.0
1,TXN659381,CUST9640,CHENNAI,2019-01-12,WITHDRAWAL,3793001.0,USD,PENDING,314819083.0
2,TXN880101,CUST3248,CALICUT,2018-01-16,WITHDRAWAL,2160839.0,INR,UNKNOWN,2160839.0
3,TXN823601,CUST2120,KOCHI,18-12-2020,WITHDRAWAL,1180522.0,USD,SUCCESS,97983326.0
4,TXN318577,CUST2707,TRIVANDRUM,09/20/2021,WITHDRAWAL,4326846.0,INR,PENDING,4326846.0

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15000 entries, 0 to 15088
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    15000 non-null  object
 1   Customer_ID       15000 non-null  object
 2   Branch            15000 non-null  object
 3   Transaction_Date  15000 non-null  object
 4   Transaction_Type  15000 non-null  object
 5   Amount            15000 non-null  float64
 6   Currency          15000 non-null  object
 7   Status            15000 non-null  object
 8   Amount_in_INR     15000 non-null  float64
dtypes: float64(2), object(7)
memory usage: 1.1+ MB

In [5]:
data=data.dropna()

In [7]:
data['Currency'].isna().sum()

3070

In [5]:
data['Currency']=data['Currency'].fillna('INR')

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15089 entries, 0 to 15088
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    15000 non-null  object
 1   Customer_ID       15000 non-null  object
 2   Branch            15000 non-null  object
 3   Transaction_Date  15000 non-null  object
 4   Transaction_Type  15000 non-null  object
 5   Amount            15000 non-null  float64
 6   Currency          15089 non-null  object
 7   Status            11891 non-null  object
dtypes: float64(1), object(7)
memory usage: 943.2+ KB

In [7]:
#Handling word case
data['Currency']=data['Currency'].str.strip().str.upper()

In [9]:
data['Branch']=data['Branch'].str.upper()

In [11]:
data['Transaction_Type']=data['Transaction_Type'].str.upper()

In [51]:
data.head(10)

,Transaction_ID,Customer_ID,Branch,Transaction_Date,Transaction_Type,Amount,Currency,Status
0,TXN833420,CUST2665,TRIVANDRUM,2023-01-07,DEPOSIT,389650.0,INR,NaN
1,TXN659381,CUST9640,CHENNAI,2019-01-12,WITHDRAWAL,3793001.0,USD,PENDING
2,TXN880101,CUST3248,CALICUT,2018-01-16,WITHDRAWAL,2160839.0,INR,NaN
3,TXN823601,CUST2120,KOCHI,18-12-2020,WITHDRAWAL,1180522.0,USD,success
4,TXN318577,CUST2707,TRIVANDRUM,09/20/2021,WITHDRAWAL,4326846.0,INR,PENDING
5,TXN446049,CUST2365,TRIVANDRUM,2020-06-06,DEPOSIT,2625184.0,INR,success
6,TXN703245,CUST9399,CHENNAI,07/19/2024,DEPOSIT,315605.0,INR,NaN
7,TXN182215,CUST5534,CHENNAI,2021-12-27,TRANSFER,4407865.0,INR,Failed
8,TXN318581,CUST7114,KOCHI,19-09-2023,WITHDRAWAL,2557583.0,INR,Failed
9,TXN381025,CUST8176,KOCHI,28-12-2023,WITHDRAWAL,173515.0,USD,Success

In [13]:
#Convert USD to INR
conversion_rate={'INR':1,'USD':83}

data['Amount_in_INR']=data.apply(lambda row: row['Amount']*conversion_rate[row['Currency']],axis=1)

In [55]:
data.head(10)

,Transaction_ID,Customer_ID,Branch,Transaction_Date,Transaction_Type,Amount,Currency,Status,Amount_in_INR
0,TXN833420,CUST2665,TRIVANDRUM,2023-01-07,DEPOSIT,389650.0,INR,NaN,389650.0
1,TXN659381,CUST9640,CHENNAI,2019-01-12,WITHDRAWAL,3793001.0,USD,PENDING,314819083.0
2,TXN880101,CUST3248,CALICUT,2018-01-16,WITHDRAWAL,2160839.0,INR,NaN,2160839.0
3,TXN823601,CUST2120,KOCHI,18-12-2020,WITHDRAWAL,1180522.0,USD,success,97983326.0
4,TXN318577,CUST2707,TRIVANDRUM,09/20/2021,WITHDRAWAL,4326846.0,INR,PENDING,4326846.0
5,TXN446049,CUST2365,TRIVANDRUM,2020-06-06,DEPOSIT,2625184.0,INR,success,2625184.0
6,TXN703245,CUST9399,CHENNAI,07/19/2024,DEPOSIT,315605.0,INR,NaN,315605.0
7,TXN182215,CUST5534,CHENNAI,2021-12-27,TRANSFER,4407865.0,INR,Failed,4407865.0
8,TXN318581,CUST7114,KOCHI,19-09-2023,WITHDRAWAL,2557583.0,INR,Failed,2557583.0
9,TXN381025,CUST8176,KOCHI,28-12-2023,WITHDRAWAL,173515.0,USD,Success,14401745.0

In [59]:
data['Status'].isna().sum()

3198

In [61]:
print((3198/15000)*100)

21.32

In [15]:
#Handling missing values in status
data['Status']=data['Status'].fillna('Unknown')

In [17]:
#Handling word case
data['Status']=data['Status'].str.strip().str.upper()

In [19]:
data.head(20)

,Transaction_ID,Customer_ID,Branch,Transaction_Date,Transaction_Type,Amount,Currency,Status,Amount_in_INR
0,TXN833420,CUST2665,TRIVANDRUM,2023-01-07,DEPOSIT,389650.0,INR,UNKNOWN,389650.0
1,TXN659381,CUST9640,CHENNAI,2019-01-12,WITHDRAWAL,3793001.0,USD,PENDING,314819083.0
2,TXN880101,CUST3248,CALICUT,2018-01-16,WITHDRAWAL,2160839.0,INR,UNKNOWN,2160839.0
3,TXN823601,CUST2120,KOCHI,18-12-2020,WITHDRAWAL,1180522.0,USD,SUCCESS,97983326.0
4,TXN318577,CUST2707,TRIVANDRUM,09/20/2021,WITHDRAWAL,4326846.0,INR,PENDING,4326846.0
5,TXN446049,CUST2365,TRIVANDRUM,2020-06-06,DEPOSIT,2625184.0,INR,SUCCESS,2625184.0
6,TXN703245,CUST9399,CHENNAI,07/19/2024,DEPOSIT,315605.0,INR,UNKNOWN,315605.0
7,TXN182215,CUST5534,CHENNAI,2021-12-27,TRANSFER,4407865.0,INR,FAILED,4407865.0
8,TXN318581,CUST7114,KOCHI,19-09-2023,WITHDRAWAL,2557583.0,INR,FAILED,2557583.0
9,TXN381025,CUST8176,KOCHI,28-12-2023,WITHDRAWAL,173515.0,USD,SUCCESS,14401745.0
10,TXN562916,CUST3481,CHENNAI,18-10-2021,DEPOSIT,3420748.0,INR,PENDING,3420748.0
11,TXN352057,CUST5495,TRIVANDRUM,2021-05-18,WITHDRAWAL,2485011.0,USD,FAILED,206255913.0
12,TXN648395,CUST4363,CALICUT,06/07/2019,TRANSFER,3860761.0,USD,SUCCESS,320443163.0
13,TXN237379,CUST7166,CHENNAI,10/10/2024,WITHDRAWAL,2732517.0,INR,FAILED,2732517.0
14,TXN554481,CUST2180,CALICUT,2024-08-01,TRANSFER,1071746.0,INR,PENDING,1071746.0
15,TXN365525,CUST5786,KOCHI,02/02/2021,DEPOSIT,4585152.0,INR,UNKNOWN,4585152.0
16,TXN250148,CUST9572,CALICUT,16-03-2024,DEPOSIT,2183836.0,USD,SUCCESS,181258388.0
17,TXN991532,CUST7151,CHENNAI,02-12-2022,DEPOSIT,3892812.0,INR,PENDING,3892812.0
18,TXN783223,CUST9605,CHENNAI,08/05/2019,WITHDRAWAL,1413388.0,USD,UNKNOWN,117311204.0
19,TXN365467,CUST2683,CALICUT,07/12/2020,DEPOSIT,3205128.0,INR,PENDING,3205128.0

In [22]:
data.to_csv('E:\Data analysis\Project\Loan\Transaction_updated.csv',index=False)

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Admin\AppData\Local\Temp\ipykernel_15236\3913322841.py:1: SyntaxWarning: invalid escape sequence '\D'
  data.to_csv('E:\Data analysis\Project\Loan\Transaction_updated.csv',index=False)

In [24]:
#Convert into datetime

#data['Transaction_Date']=pd.to_datetime(data['Transaction_Date'],errors='coerce',dayfirst=True)

#convert into standardize into one format

#data['Transaction_date']=data['Transaction_Date'].dt.strftime('%Y-%m-%d')

In [7]:
data.head()

,Transaction_ID,Customer_ID,Branch,Transaction_Date,Transaction_Type,Amount,Currency,Status,Amount_in_INR
0,TXN833420,CUST2665,TRIVANDRUM,2023-01-07,DEPOSIT,389650.0,INR,UNKNOWN,389650.0
1,TXN659381,CUST9640,CHENNAI,2019-01-12,WITHDRAWAL,3793001.0,USD,PENDING,314819083.0
2,TXN880101,CUST3248,CALICUT,2018-01-16,WITHDRAWAL,2160839.0,INR,UNKNOWN,2160839.0
3,TXN823601,CUST2120,KOCHI,18-12-2020,WITHDRAWAL,1180522.0,USD,SUCCESS,97983326.0
4,TXN318577,CUST2707,TRIVANDRUM,09/20/2021,WITHDRAWAL,4326846.0,INR,PENDING,4326846.0

In [7]:
from datetime import datetime

def parse_date(x):
    for fmt in('%Y-%m-%d','%d-%m-%Y','%m/%d/%Y'):
        try:
            return datetime.strptime(x, fmt)
        except ValueError:
            continue
    return pd.NaT

data1['Transaction_Date']=data1['Transaction_Date'].apply(parse_date)


data1['Transaction_Date']=data1['Transaction_Date'].dt.strftime('%Y-%m-%d')

In [9]:
data.head(30)

,Transaction_ID,Customer_ID,Branch,Transaction_Date,Transaction_Type,Amount,Currency,Status,Amount_in_INR
0,TXN833420,CUST2665,TRIVANDRUM,2023-01-07,DEPOSIT,389650.0,INR,UNKNOWN,389650.0
1,TXN659381,CUST9640,CHENNAI,2019-01-12,WITHDRAWAL,3793001.0,USD,PENDING,314819083.0
2,TXN880101,CUST3248,CALICUT,2018-01-16,WITHDRAWAL,2160839.0,INR,UNKNOWN,2160839.0
3,TXN823601,CUST2120,KOCHI,2020-12-18,WITHDRAWAL,1180522.0,USD,SUCCESS,97983326.0
4,TXN318577,CUST2707,TRIVANDRUM,2021-09-20,WITHDRAWAL,4326846.0,INR,PENDING,4326846.0
5,TXN446049,CUST2365,TRIVANDRUM,2020-06-06,DEPOSIT,2625184.0,INR,SUCCESS,2625184.0
6,TXN703245,CUST9399,CHENNAI,2024-07-19,DEPOSIT,315605.0,INR,UNKNOWN,315605.0
7,TXN182215,CUST5534,CHENNAI,2021-12-27,TRANSFER,4407865.0,INR,FAILED,4407865.0
8,TXN318581,CUST7114,KOCHI,2023-09-19,WITHDRAWAL,2557583.0,INR,FAILED,2557583.0
9,TXN381025,CUST8176,KOCHI,2023-12-28,WITHDRAWAL,173515.0,USD,SUCCESS,14401745.0
10,TXN562916,CUST3481,CHENNAI,2021-10-18,DEPOSIT,3420748.0,INR,PENDING,3420748.0
11,TXN352057,CUST5495,TRIVANDRUM,2021-05-18,WITHDRAWAL,2485011.0,USD,FAILED,206255913.0
12,TXN648395,CUST4363,CALICUT,2019-06-07,TRANSFER,3860761.0,USD,SUCCESS,320443163.0
13,TXN237379,CUST7166,CHENNAI,2024-10-10,WITHDRAWAL,2732517.0,INR,FAILED,2732517.0
14,TXN554481,CUST2180,CALICUT,2024-08-01,TRANSFER,1071746.0,INR,PENDING,1071746.0
15,TXN365525,CUST5786,KOCHI,2021-02-02,DEPOSIT,4585152.0,INR,UNKNOWN,4585152.0
16,TXN250148,CUST9572,CALICUT,2024-03-16,DEPOSIT,2183836.0,USD,SUCCESS,181258388.0
17,TXN991532,CUST7151,CHENNAI,2022-12-02,DEPOSIT,3892812.0,INR,PENDING,3892812.0
18,TXN783223,CUST9605,CHENNAI,2019-08-05,WITHDRAWAL,1413388.0,USD,UNKNOWN,117311204.0
19,TXN365467,CUST2683,CALICUT,2020-07-12,DEPOSIT,3205128.0,INR,PENDING,3205128.0
20,TXN435539,CUST4288,KOCHI,2021-03-20,WITHDRAWAL,3862653.0,INR,FAILED,3862653.0
21,TXN576572,CUST3069,CHENNAI,2022-06-15,DEPOSIT,3342715.0,INR,UNKNOWN,3342715.0
22,TXN825091,CUST7618,CALICUT,2019-07-31,WITHDRAWAL,2748838.0,INR,SUCCESS,2748838.0
23,TXN570969,CUST7306,TRIVANDRUM,2018-03-23,DEPOSIT,3451035.0,INR,PENDING,3451035.0
24,TXN592045,CUST5891,CALICUT,2023-11-19,DEPOSIT,1929270.0,INR,FAILED,1929270.0
25,TXN114844,CUST3569,TRIVANDRUM,2019-02-07,DEPOSIT,620741.0,INR,SUCCESS,620741.0
26,TXN967865,CUST4273,CALICUT,2019-11-08,WITHDRAWAL,847835.0,USD,PENDING,70370305.0
27,TXN734133,CUST4135,KOCHI,2021-03-28,WITHDRAWAL,1477099.0,INR,UNKNOWN,1477099.0
28,TXN727762,CUST9056,KOCHI,2019-07-23,WITHDRAWAL,857028.0,USD,UNKNOWN,71133324.0
29,TXN162565,CUST5098,CHENNAI,2019-04-28,DEPOSIT,625698.0,INR,SUCCESS,625698.0

In [13]:
data.to_csv('E:/Data Analysis/Project/Loan/Transactn1.csv',index=False)

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15000 entries, 0 to 15088
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    15000 non-null  object
 1   Customer_ID       15000 non-null  object
 2   Branch            15000 non-null  object
 3   Transaction_Date  15000 non-null  object
 4   Transaction_Type  15000 non-null  object
 5   Amount            15000 non-null  float64
 6   Currency          15000 non-null  object
 7   Status            15000 non-null  object
 8   Amount_in_INR     15000 non-null  float64
dtypes: float64(2), object(7)
memory usage: 1.1+ MB

In [9]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        15000 non-null  int64
 1   Transaction_ID    15000 non-null  object
 2   Customer_ID       15000 non-null  object
 3   Branch            15000 non-null  object
 4   Transaction_Date  15000 non-null  object
 5   Transaction_Type  15000 non-null  object
 6   Amount            15000 non-null  float64
 7   Currency          15000 non-null  object
 8   Status            15000 non-null  object
 9   Amount_in_INR     15000 non-null  float64
dtypes: float64(2), int64(1), object(7)
memory usage: 1.1+ MB

In [3]:
data1=pd.read_csv('Transactn1.csv')

In [11]:
data1['Status']=data1['Status'].str.strip().str.upper()

In [13]:
data1['Currency']=data1['Currency'].str.strip().str.upper()

In [15]:
data1['Transaction_Type']=data1['Transaction_Type'].str.strip().str.upper()

In [5]:
data1['Branch']=data1['Branch'].str.strip().str.upper()

In [5]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        15000 non-null  int64
 1   Transaction_ID    15000 non-null  object
 2   Customer_ID       15000 non-null  object
 3   Branch            15000 non-null  object
 4   Transaction_Date  15000 non-null  object
 5   Transaction_Type  15000 non-null  object
 6   Amount            15000 non-null  float64
 7   Currency          15000 non-null  object
 8   Status            15000 non-null  object
 9   Amount_in_INR     15000 non-null  float64
dtypes: float64(2), int64(1), object(7)
memory usage: 1.1+ MB

In [11]:
data1.to_csv(r'E:\Data Analysis\Project\Loan\Transactn1.csv',index=False)

In [5]:
data1=data1.drop(columns=['Unnamed: 0'])

In [7]:
data1['Transaction_Date']=pd.to_datetime(data1['Transaction_Date'])

In [9]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    15000 non-null  object
 1   Customer_ID       15000 non-null  object
 2   Branch            15000 non-null  object
 3   Transaction_Date  15000 non-null  datetime64[ns]
 4   Transaction_Type  15000 non-null  object
 5   Amount            15000 non-null  float64
 6   Currency          15000 non-null  object
 7   Status            15000 non-null  object
 8   Amount_in_INR     15000 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 1.0+ MB

In [15]:
data1.head(20)

,Transaction_ID,Customer_ID,Branch,Transaction_Date,Transaction_Type,Amount,Currency,Status,Amount_in_INR
0,TXN833420,CUST2665,TRIVANDRUM,2023-01-07,DEPOSIT,389650.0,INR,UNKNOWN,389650.0
1,TXN659381,CUST9640,CHENNAI,2019-01-12,WITHDRAWAL,3793001.0,USD,PENDING,314819083.0
2,TXN880101,CUST3248,CALICUT,2018-01-16,WITHDRAWAL,2160839.0,INR,UNKNOWN,2160839.0
3,TXN823601,CUST2120,KOCHI,2020-12-18,WITHDRAWAL,1180522.0,USD,SUCCESS,97983326.0
4,TXN318577,CUST2707,TRIVANDRUM,2021-09-20,WITHDRAWAL,4326846.0,INR,PENDING,4326846.0
5,TXN446049,CUST2365,TRIVANDRUM,2020-06-06,DEPOSIT,2625184.0,INR,SUCCESS,2625184.0
6,TXN703245,CUST9399,CHENNAI,2024-07-19,DEPOSIT,315605.0,INR,UNKNOWN,315605.0
7,TXN182215,CUST5534,CHENNAI,2021-12-27,TRANSFER,4407865.0,INR,FAILED,4407865.0
8,TXN318581,CUST7114,KOCHI,2023-09-19,WITHDRAWAL,2557583.0,INR,FAILED,2557583.0
9,TXN381025,CUST8176,KOCHI,2023-12-28,WITHDRAWAL,173515.0,USD,SUCCESS,14401745.0
10,TXN562916,CUST3481,CHENNAI,2021-10-18,DEPOSIT,3420748.0,INR,PENDING,3420748.0
11,TXN352057,CUST5495,TRIVANDRUM,2021-05-18,WITHDRAWAL,2485011.0,USD,FAILED,206255913.0
12,TXN648395,CUST4363,CALICUT,2019-06-07,TRANSFER,3860761.0,USD,SUCCESS,320443163.0
13,TXN237379,CUST7166,CHENNAI,2024-10-10,WITHDRAWAL,2732517.0,INR,FAILED,2732517.0
14,TXN554481,CUST2180,CALICUT,2024-08-01,TRANSFER,1071746.0,INR,PENDING,1071746.0
15,TXN365525,CUST5786,KOCHI,2021-02-02,DEPOSIT,4585152.0,INR,UNKNOWN,4585152.0
16,TXN250148,CUST9572,CALICUT,2024-03-16,DEPOSIT,2183836.0,USD,SUCCESS,181258388.0
17,TXN991532,CUST7151,CHENNAI,2022-12-02,DEPOSIT,3892812.0,INR,PENDING,3892812.0
18,TXN783223,CUST9605,CHENNAI,2019-08-05,WITHDRAWAL,1413388.0,USD,UNKNOWN,117311204.0
19,TXN365467,CUST2683,CALICUT,2020-07-12,DEPOSIT,3205128.0,INR,PENDING,3205128.0